### ISSUE TITLE
emperor.uwsgi.service confusion

### ISSUE THREAD

**Issue by zopagaduanjr** [futureshocked/RaspberryPiFullStack_Raspbian#9]
For those who followed the 2015 tutorial (Minibian OS), you should change the line 
ExecStart=/var/www/lab_app/bin/uwsgi --ini /var/www/lab_app/lab_app_uwsgi.ini
into 
ExecStart=/var/www/lab_app/venv/bin/uwsgi --ini /var/www/lab_app/lab_app_uwsgi.ini
This is because we are inside venv while installing flask and uwsgi inside pip.
I've been troubleshooting for 2 hours and I don't want others to feel the same agony.

**Comment by pragathoys** [comment]
Hi ,
for the old course (RPFS minibian) this might be true, but in this newer course we are not creating the Virtual Python Environment within a 'venv' folder but directly inside the 'lab_app' folder. So the line:
ExecStart=/var/www/lab_app/bin/uwsgi --ini /var/www/lab_app/lab_app_uwsgi.ini

is correct.
